### ISSUE TITLE
Use versioneer from subdirectory

### ISSUE THREAD

**Issue by smessmer** [warner/python-versioneer#109] opened 2016-03-02 01:05 UTC
I'd like to use versioneer in a non-python (C++) project and have it offer a version string which can be used by CMake in my build process.

For this, I created a small python script that can be called from CMake and just outputs the version information:

    #!/usr/bin/env python
    import versioneer
    print versioneer.get_version()

Works fine so far.
However, since this is not a python project, I don't like having the python files hanging around in the source tree root, so I created a subdirectory and moved everything there. When I call it from there, it reports version "0-unknown". I'm wondering why this happens - git commands should be runnable from a subdirectory as well. Maybe it is looking for the .git directory and doesn't find it.

Could you make versioneer work when it is stored in a subdirectory?

**Comment by isnok** [comment] 2016-03-21 21:04
Hello, and +1!

I have exactly the same request (and even for a python project :).

I dug around the sources for a while, and came to the conclusion, that versioneer seems to assume, that the .git directory is always right next to setup.py. Now that is not true for my current project. In fact I have ~5 setup.py-s in sudirectories. Some fiddling around involving links got me to the point, where I got a version number directly from _version.py, but versioneer.py (from the repo, not the environment...) was somehow not able to produce that, and so my setup.py won't get anything from there.

versioneer looks like a good project to me in general, so if you need help in fixing that, I might be someone who can help. I see a lot more use-cases (because that's why i looked at it in the first place), once this is implemented.

**Comment by isnok** [comment] 2016-03-21 21:09
Just found https://github.com/warner/python-versioneer/issues/38, and it looks as if this one is a duplicate of that.

Nice to notice, that it carries a small icon indicating that it's planned for the next release.

**Comment by warner** [comment] 2016-04-12 16:51
Closing as a duplicate of #38 (which has an updated branch now). Thanks for digging into it!

**Closed by warner** 2016-04-12 16:51 UTC
